name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=shadow_red&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.PAT }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=shadow_red&layout=compact&langs_count=6
          path: profile/top-langs.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card for Pebblify
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=dockermint&repo=pebblify&theme=shadow_red
          path: profile/pin-dockermint-pebblify.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card for EVM Indexer
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=nayrosk&repo=evm-indexer&theme=shadow_red
          path: profile/pin-nayrosk-evm-indexer.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card for MX Chain Keys Monitor Go
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=nayrosk&repo=mx-chain-keys-monitor-go&theme=shadow_red
          path: profile/pin-nayrosk-mx-chain-keys-monitor-go.svg
          token: ${{ secrets.PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
